{{- if and .Values.database.createSecret (not .Values.database.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "telemetry-api-gateway.secretName" . }}
  labels:
    {{- include "telemetry-api-gateway.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.database.existingSecretKey }}: {{ .Values.database.url | quote }}
{{- end }}
